import { ENV } from '@/config/env.config';

/**
 * Represents a customer in the commercial module.
 */
export interface Cliente {
  /** Unique identifier of the customer. */
  id: number;
  /** Customer's name or business name. */
  nombre: string;
  /** CUIT or CUIL number of the customer. */
  cuit_cuil: string;
  /** Email address of the customer. */
  email: string;
}

/**
 * Represents a logged sale with basic information.
 */
export interface Venta {
  /** Unique identifier of the sale. */
  id: number;
  /** Reference identifier of the customer who bought. */
  cliente_id: number;
  /** Optional customer name. */
  cliente?: string;
  /** ISO timestamp/date string representing when the sale took place. */
  fecha_venta: string;
  /** Total cost amount of the sale. */
  total: number;
  /** Payment method used (e.g. 'Efectivo', 'Tarjeta'). */
  metodo_pago: string;
  /** Optional invoice number generated by the system. */
  nro_factura?: string;
  /** Optional Authorization Code (CAE) from AFIP. */
  cae?: string;
  /** Transaction currency. */
  moneda: 'ARS' | 'USD';
}

/**
 * Shape returned by the backend in GET /ventas before parsing.
 */
export interface VentaRaw {
  /** Unique identifier of the raw sale record. */
  id: number;
  /** Reference identifier of the customer. */
  cliente_id: number;
  /** Optional customer name. */
  cliente?: string;
  /** Optional sale date. */
  fecha_venta?: string;
  /** Optional alternative sale date. */
  fecha?: string;
  /** Raw total amount (could be string or number from API). */
  total: number | string;
  /** Payment method. */
  metodo_pago: string;
  /** Invoice number. */
  nro_factura?: string;
  /** AFIP CAE code. */
  cae?: string;
  /** Currency of the sale. */
  moneda?: 'ARS' | 'USD';
}

/**
 * Represents a specific mannequin item inside a sale detail record.
 */
export interface DetalleVentaItem {
  /** Unique identifier of the sold mannequin. */
  maniqui_id: number;
  /** Serial number of the sold mannequin. */
  numero_serie: string;
  /** Final unit price at which the mannequin was sold. */
  precio_final: number;
  /** Nested model reference containing the model name. */
  Modelo?: { nombre: string };
  /** Nested mannequin reference with serial number and model name. */
  maniqui?: { numero_serie?: string; Modelo?: { nombre: string } };
}

/**
 * Full details of a sale including the individual items sold.
 */
export interface VentaDetalle extends Venta {
  /** List of mannequin items sold in this transaction. */
  Detalle_Ventas: DetalleVentaItem[];
}

/**
 * Represents a mannequin in the inventory.
 */
export interface Maniqui {
  /** Unique identifier of the mannequin. */
  id: number;
  /** Serial number of the mannequin. */
  numero_serie: string;
  /** Reference identifier of the mannequin's design model. */
  modelo_id: number;
  /** Current status of the mannequin (e.g. 'Disponible', 'Vendido'). */
  status: string;
  /** Nested model metadata. */
  Modelo?: {
    /** Name of the model. */
    nombre: string;
    /** Suggested sale price. */
    precio_venta?: number | string;
  };
}

/**
 * Service providing API calls for commercial/sales operations.
 */
export const comercialService = {
  /**
   * Fetches all registered customers.
   *
   * @param token - Authentication bearer token.
   * @returns List of customers.
   * @throws Session expired error or general load error.
   */
  getClientes: async (token: string): Promise<Cliente[]> => {
    const response = await fetch(`${ENV.API_URL}/clientes`, {
      headers: { 'Authorization': `Bearer ${token}` }
    });
    if (response.status === 401) throw new Error('auth.error.session_expired');
    if (!response.ok) throw new Error('Error al cargar clientes');
    return response.json();
  },

  /**
   * Creates a new customer.
   *
   * @param token - Authentication bearer token.
   * @param data - New customer data.
   * @returns The created customer object.
   * @throws Session expired or API validation error.
   */
  createCliente: async (token: string, data: { nombre: string; cuit_cuil: string; email: string }): Promise<Cliente> => {
    const response = await fetch(`${ENV.API_URL}/clientes`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(data)
    });
    if (response.status === 401) throw new Error('auth.error.session_expired');
    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      const msg = errData.errores?.[0]?.msg || errData.error || 'Error al crear cliente';
      throw new Error(msg);
    }
    return response.json();
  },

  /**
   * Fetches all sales records.
   *
   * @param token - Authentication bearer token.
   * @returns Raw list of sales records.
   * @throws Session expired or load error.
   */
  getVentas: async (token: string): Promise<VentaRaw[]> => {
    const response = await fetch(`${ENV.API_URL}/ventas`, {
      headers: { 'Authorization': `Bearer ${token}` }
    });
    if (response.status === 401) throw new Error('auth.error.session_expired');
    if (!response.ok) throw new Error('Error al cargar ventas');
    return response.json();
  },

  /**
   * Fetches a detailed sale record by its ID.
   *
   * @param token - Authentication bearer token.
   * @param id - ID of the sale.
   * @returns Sale details including item breakdown.
   * @throws Session expired or load error.
   */
  getVentaById: async (token: string, id: number): Promise<VentaDetalle> => {
    const response = await fetch(`${ENV.API_URL}/ventas/${id}`, {
      headers: { 'Authorization': `Bearer ${token}` }
    });
    if (response.status === 401) throw new Error('auth.error.session_expired');
    if (!response.ok) throw new Error('Error al cargar detalle de venta');
    return response.json();
  },

  /**
   * Registers a new sale transaction.
   *
   * @param token - Authentication bearer token.
   * @param data - Details of the sale.
   * @returns The registered sale summary.
   * @throws Session expired or registration error.
   */
  createVenta: async (token: string, data: { cliente_id: number; metodo_pago: string; moneda: string; maniquies: { maniqui_id: number; precio_final: number }[] }): Promise<Venta> => {
    const response = await fetch(`${ENV.API_URL}/ventas`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(data)
    });
    if (response.status === 401) throw new Error('auth.error.session_expired');
    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      const msg = errData.errores?.[0]?.msg || errData.error || 'Error al registrar venta';
      throw new Error(msg);
    }
    return response.json();
  },

  /**
   * Fetches all mannequins currently available for sale.
   *
   * @param token - Authentication bearer token.
   * @returns List of available mannequins.
   * @throws Session expired or load error.
   */
  getManiquiesDisponibles: async (token: string): Promise<Maniqui[]> => {
    const response = await fetch(`${ENV.API_URL}/maniquies?status=Disponible`, {
      headers: { 'Authorization': `Bearer ${token}` }
    });
    if (response.status === 401) throw new Error('auth.error.session_expired');
    if (!response.ok) throw new Error('Error al cargar maniquíes disponibles');
    return response.json();
  }
};
